services:
  app:
    image: container-iyklgni
    build:
      context: ./src
    ports:
      - "5000:5000"
    env_file:
      - web.env
    volumes:
      - type: bind
        source: ./src/web
        target: /usr/src/app
      - type: bind
        source: ./keys
        target: /root/.ssh
